### ISSUE TITLE
定位有点杂

### ISSUE THREAD

**Issue by runhey** [NakanoSanku/minidevice#1]
一开始看文档甚至没有弄懂你的思路，建议写一些简述。
我不太能理解会塞入一些图色的操作，然后貌似中途又塞入window的操作。

咱就是说可以先列一个todo，以上

**Comment by NakanoSanku** [comment]
非常抱歉，确实很混乱，已经重写了api文档(含每个截图方法\操作方法的参数说明以及各方法的使用示例)
(第一次写这种不太了解)

**Comment by NakanoSanku** [comment]
截至目前minidevice==2.3.3，应该算是理清并且完善这个项目，详情见最新的更新
