### ISSUE TITLE
库有问题

### ISSUE THREAD

**Issue by SIXGODLI** [NakanoSanku/minidevice#11]
Traceback (most recent call last):
  File "D:\minidevice\main.py", line 4, in <module>
    from minidevicemumuapi import *
ModuleNotFoundError: No module named 'minidevicemumuapi'

**Comment by NakanoSanku** [comment]
抱歉这个main方法中的代码是测试 [mumuapi](https://github.com/NakanoSanku/minidevice/tree/minidevice-mumuapi) 分支的,不是主分支内容
