### ISSUE TITLE
screenshot_raw的每次调用都会关闭/开启一次minicap

### ISSUE THREAD

**Issue by Z-eddy** [NakanoSanku/minidevice#3]
每次MiniDevice调用screenshot_raw方法，都会触发MiniCap的关闭、重启，具体的触发地方在这里：

https://github.com/NakanoSanku/minidevice/blob/cc138a606be0fb6aef2ce116ef39bbffa8b46cbd/minidevice/minicap.py#L223

**Comment by NakanoSanku** [comment]
我这边实测并不会，麻烦提供一下具体日志

**Comment by Z-eddy** [comment]
刚刚测试了下，恢复了昨天的测试状态，的确无法复现了
